### ISSUE TITLE
New Sign-In Detected Authentication Error

### ISSUE THREAD

**Issue by stanley-twobrick** [dlabrie/shakingbot#1]
Logging in with login.py I get the message 'New login detected, please verify your device through the security email we just sent you.'

Verified the email but shake.py still says NotAuthenticated and I can't rerun login.py:

![screenshot](https://user-images.githubusercontent.com/97919524/149840657-b9880be3-97a0-4126-860f-a9feb73b1bdb.png)
y

**Comment by dlabrie** [comment]
Delete the following file: .jwtToken
